### ISSUE TITLE
Another story (story_2)

### ISSUE THREAD

**Issue by chrisvdg** [chrisvdg/storybot_test#4]
## Tasks

- [x] [This is a very useful task indeed!](https://github.com/chrisvdg/storybot_test/issues/9)
- [x] [Lorem Ipsum](https://github.com/chrisvdg/storybot_test/issues/7)
- [ ] [foo bars](https://github.com/chrisvdg/storybot_test/issues/5)
- [ ] [Bran I](https://docs.greenitglobe.com/chris.vandegejuchte/hello_world/issues/5)
